import json
import logging
import os
import re
import time

import httpx

from app.models.schemas import Finding

# Configure logging
logger = logging.getLogger(__name__)

MAX_RETRIES = 3
RETRY_DELAYS = [2, 5, 10]


def build_insights(content: str, findings: list[Finding], risk_level: str) -> tuple[str, list[str], str]:
    if not findings:
        logger.debug("No findings detected, using default insights")
        return (
            "No sensitive patterns detected in the submitted content.",
            ["No immediate security risks found."],
            "rules",
        )

    llm_result, llm_error = _build_llm_insights(content, findings, risk_level)
    if llm_result:
        summary, insights, provider = llm_result
        logger.info(f"LLM insights generated by provider: {provider}")
        return summary, insights, f"llm:{provider}"

    # Fall back to rule-based insights
    logger.warning(f"LLM insights failed ({llm_error}), using rule-based fallback")
    summary = f"Detected {len(findings)} risk pattern(s) with overall risk level '{risk_level}'."
    finding_types = sorted({f.type for f in findings})
    insights = [f"Detected categories: {', '.join(finding_types)}."]

    if any(f.type == "password" for f in findings):
        insights.append("Credentials appear in logs and should be removed or masked immediately.")

    if any(f.type == "stack_trace" for f in findings):
        insights.append("Stack traces may expose internal implementation details.")

    if any(f.type == "brute_force_suspected" for f in findings):
        insights.append("Possible brute-force activity detected due to repeated authentication failures.")

    if len(content.splitlines()) > 500:
        insights.append("Large log detected; enable chunking for better performance and traceability.")

    if llm_error == "no_provider_configured":
        insights.append("LLM is not configured. Set LLM provider values in ai-service/.env for AI-generated insights.")
    else:
        insights.append(f"LLM call failed ({llm_error}). Showing rule-based insights.")

    return summary, insights, "rules"


def _build_llm_insights(content: str, findings: list[Finding], risk_level: str) -> tuple[tuple[str, list[str], str] | None, str | None]:
    providers = _get_provider_candidates()
    if not providers:
        logger.warning("No LLM providers configured")
        return None, "no_provider_configured"

    logger.debug(f"Attempting LLM insights with {len(providers)} provider(s)")

    findings_payload = [
        {"type": f.type, "risk": f.risk, "line": f.line, "value": f.value} for f in findings[:30]
    ]
    snippet = "\n".join(content.splitlines()[:120])

    system_prompt = (
        "You are a security log analyst. You MUST return ONLY valid JSON with exactly two keys: "
        '"summary" (a string) and "insights" (an array of strings). '
        "Do NOT wrap the JSON in markdown code fences. Keep output concise and actionable."
    )
    user_prompt = {
        "risk_level": risk_level,
        "findings": findings_payload,
        "log_snippet": snippet,
        "instructions": "Explain real security impact and remediation; avoid generic statements.",
    }

    request_body_base = {
        "temperature": 0.2,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": json.dumps(user_prompt)},
        ],
    }

    for provider in providers:
        last_error = None
        logger.debug(f"Trying LLM provider: {provider['name']}")

        for attempt in range(MAX_RETRIES):
            request_body = dict(request_body_base)
            request_body["model"] = provider["model"]

            headers = {
                "Authorization": f"Bearer {provider['api_key']}",
                "Content-Type": "application/json",
            }
            if "openrouter.ai" in provider["base_url"]:
                headers["HTTP-Referer"] = "http://localhost:5173"
                headers["X-Title"] = "AI Secure Data Intelligence Platform"

            url = f"{provider['base_url'].rstrip('/')}/chat/completions"

            try:
                with httpx.Client(timeout=45.0) as client:
                    response = client.post(url, headers=headers, json=request_body)

                if response.status_code == 429:
                    delay = RETRY_DELAYS[attempt] if attempt < len(RETRY_DELAYS) else 10
                    logger.debug(
                        f"Rate limited by {provider['name']}, retrying in {delay}s "
                        f"(attempt {attempt + 1}/{MAX_RETRIES})"
                    )
                    time.sleep(delay)
                    last_error = "rate_limited"
                    continue

                if response.status_code != 200:
                    last_error = f"http_{response.status_code}"
                    logger.debug(f"HTTP {response.status_code} from {provider['name']}")
                    break

                raw_content = response.json()["choices"][0]["message"]["content"]
                parsed = _extract_json(raw_content)
                if parsed is None:
                    last_error = "invalid_json_response"
                    logger.debug(f"Failed to parse JSON response from {provider['name']}")
                    break

                summary = parsed.get("summary")
                insights = parsed.get("insights")
                if isinstance(summary, str) and isinstance(insights, list) and insights:
                    logger.info(f"Successfully generated LLM insights from {provider['name']}")
                    return (summary, [str(item) for item in insights[:6]], provider["name"]), None

                last_error = "missing_summary_or_insights"
                logger.debug(f"Response missing required fields from {provider['name']}")
                break
            except httpx.TimeoutException:
                last_error = "timeout"
                logger.debug(f"Timeout calling {provider['name']} (attempt {attempt + 1}/{MAX_RETRIES})")
                if attempt < MAX_RETRIES - 1:
                    time.sleep(RETRY_DELAYS[attempt])
                    continue
            except Exception as e:
                last_error = type(e).__name__
                logger.error(f"Exception calling {provider['name']}: {last_error}: {str(e)}")
                break

        if last_error:
            logger.warning(f"Provider {provider['name']} failed: {last_error}")

    logger.error("All LLM providers failed, using rule-based fallback")
    return None, "all_providers_failed"


def _get_provider_candidates() -> list[dict]:
    providers: list[dict] = []

    primary_key = os.getenv("LLM_API_KEY")
    primary_model = os.getenv("LLM_MODEL")
    primary_base = os.getenv("LLM_BASE_URL")
    if primary_key and primary_model and primary_base:
        providers.append(
            {
                "name": os.getenv("LLM_PROVIDER_NAME", "primary"),
                "api_key": primary_key,
                "model": primary_model,
                "base_url": primary_base,
            }
        )

    fallback_key = os.getenv("LLM_FALLBACK_API_KEY")
    fallback_model = os.getenv("LLM_FALLBACK_MODEL")
    fallback_base = os.getenv("LLM_FALLBACK_BASE_URL")
    if fallback_key and fallback_model and fallback_base:
        providers.append(
            {
                "name": os.getenv("LLM_FALLBACK_PROVIDER_NAME", "fallback"),
                "api_key": fallback_key,
                "model": fallback_model,
                "base_url": fallback_base,
            }
        )

    return providers


def _extract_json(text: str) -> dict | None:
    """Try to extract valid JSON from LLM output, handling markdown fences."""
    # Try direct parse first
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Try extracting from markdown code fences
    fence_match = re.search(r"```(?:json)?\s*\n?(.*?)\n?```", text, re.DOTALL)
    if fence_match:
        try:
            return json.loads(fence_match.group(1).strip())
        except json.JSONDecodeError:
            pass

    # Try finding first { ... } block
    brace_match = re.search(r"\{.*\}", text, re.DOTALL)
    if brace_match:
        try:
            return json.loads(brace_match.group(0))
        except json.JSONDecodeError:
            pass

    return None
